## Each new term in the Fibonacci sequence is generated by adding the previous two terms.
## By starting with 1 and 2, the first 10 terms will be:

## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

## By considering the terms in the Fibonacci sequence whose values do not exceed
## four million, find the sum of the even-valued terms.

def fibs(n):
	L = [1, 1]
	j = 1
	k = 1
	for i in range (1, n-1):
		sum = j + k
		L.append(sum)
		j = k
		k = sum
	return L
			


L = fibs(10000)
sum = 0
for i in L:
	if i%2 == 0:
		sum += i
		if sum >= 4000000:
			break
print (sum)

